server:
  port: 8103

spring:
  application:
    name: employees
  datasource:
    url: jdbc:mysql://localhost:3308/employeesdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 3MB


upload:
  path: D:\udpt\images

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

jwt:
  key: hePrX3lreiS3uE8ESeBIkcc+4NynKRSQRT0DqWdxY/o=

info:
  app:
    name: "employees"
    description: "Hospital Management System Employees Services"