server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: accounts
              uri: lb://ACCOUNTS
              predicates:
                - Path=/api/v1/accounts/**, /api/v1/register/**
              filters:
                - StripPrefix=0
            - id: auth
              uri: lb://AUTH
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=0
            - id: patients
              uri: lb://PATIENTS
              predicates:
                - Path=/api/v1/patients/**, /api/v1/records/**
              filters:
                - StripPrefix=0
            - id: employees
              uri: lb://EMPLOYEES
              predicates:
                - Path=/api/v1/departments/**, /api/v1/schedules/**, /api/v1/employees/**
              filters:
                - StripPrefix=0
            - id: appointments
              uri: lb://APPOINTMENTS
              predicates:
                - Path=/api/v1/appointments/**, /api/v1/services/**, /api/v1/service-designation
              filters:
                - StripPrefix=0
            - id: medication
              uri: lb://MEDICATION
              predicates:
                - Path=/api/v1/medications/**, /api/v1/prescriptions/**
              filters:
                - StripPrefix=0
            - id: statistics
              uri: lb://STATISTICS
              predicates:
                - Path=/api/v1/statistics/**
              filters:
                - StripPrefix=0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka


info:
  app:
    name: "api-gateway"
    description: "Hospital Management System API Gateway"

