server:
  port: 8101

spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3308/accountsdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: always
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

jwt:
  key: hePrX3lreiS3uE8ESeBIkcc+4NynKRSQRT0DqWdxY/o=

info:
  app:
    name: "accounts"
    description: "Hospital Management System Accounts Services"

