server:
  port: 8104

spring:
  application:
    name: appointments
  datasource:
    write:
      jdbc-url: jdbc:mysql://localhost:3308/appointments_writedb
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    read:
      jdbc-url: jdbc:mysql://localhost:3308/appointments_readdb
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guess
      password: guess

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

jwt:
  key: hePrX3lreiS3uE8ESeBIkcc+4NynKRSQRT0DqWdxY/o=

info:
  app:
    name: "appointments"
    description: "Hospital Management System Appointments Services"

logging:
  level:
    org:
      springframework:
        amqp: debug