server:
  port: 8106

spring:
  application:
    name: statistics

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

jwt:
  key: hePrX3lreiS3uE8ESeBIkcc+4NynKRSQRT0DqWdxY/o=

info:
  app:
    name: "statistics"
    description: "Hospital Management System Statistics Services"
