server:
  port: 8106

spring:
  application:
    name: statistics

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

info:
  app:
    name: "statistics"
    description: "Hospital Management System Statistics Services"
