server:
  port: 8102

spring:
  application:
    name: patients
  datasource:
    url: jdbc:mysql://localhost:3308/patientsdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

jwt:
  key: hePrX3lreiS3uE8ESeBIkcc+4NynKRSQRT0DqWdxY/o=

info:
  app:
    name: "patients"
    description: "Hospital Management System Patients Services"
logging:
  level:
    org.springframework.security: DEBUG
